# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DroneBarcode' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'DJI-SDK-iOS', '~> 4.7'
  pod 'CocoaMQTT'

  target 'DroneBarcodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DroneBarcodeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
